version: '2'

services:
  pg:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=datus_integration
    ports:
      - 5432:5432
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=datus_integration
    ports:
      - 3306:3306
